GET http://localhost:8080/users?NameSearch=luis+almonaci2d&StatusSearch=&GenderSearch=&birthdateSearchFrom=&birthdateSearchTo=&createdAtSearchFrom=&createdAtSearchTo=&UpdatedAtSearchFrom=&UpdatedAtSearchTo= HTTP/1.1
Content-Type: application/json


###
GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json


###
PUT http://localhost:8080/users/65ee6bad4f38a5588d0b4b2f HTTP/1.1
Content-Type: application/json

{
 
      "name": "Luis Almonacid",
      "email": "b9S6d@example.com",
      "phone":    "123456789",
      "birthdate": "1995-03-05",
      "gender": "male"

    
}
###
DELETE http://localhost:8080/users/65ee68a05b17015c639f362b HTTP/1.1
Content-Type: application/json
###

GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json


###